// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E修改编辑框内容():Promise<string>;

export function E按钮1被点击():Promise<string>;

export function Greet(arg1:string):Promise<string>;
