name: WailsBuild

on:
  workflow_dispatch:
#  push:
#    paths-ignore:
#      - '**/*.md'
#      - '**/*.yml'
#      - .gitignore
#      - .editorconfig
#      - appveyor.yml
#      - 'azure-pipelines*.yml'
#      - 'ci/azure-pipelines/template*.yml'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

jobs:

  build-windows:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |

            C:\npm\cache
          key: ${{ runner.os }}-js-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-js-

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          cache-dependency-path: |
            **/go.sum
            **/go.mod
          go-version-file: 'go.mod'

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      #- name: install webview2
      #  run: |
      #    npm config get cache
      #    choco install webview2-runtime

        #- name: garble
        #  run: go install mvdan.cc/garble@latest

        #- name: nsis
        # run: choco install nsis

        #- name: upx
        #  run: choco install upx

      - name: build
        run: |
          cd GoEasyDesigner
          wails build -debug 


      - uses: actions/upload-artifact@v3
        with:
          name: debug-${{ runner.os }}
          path: GoEasyDesigner/build/bin/GoEasyDesigner.exe


  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |

            /home/runner/.npm
          key: ${{ runner.os }}-js-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-js-

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          cache-dependency-path: |
            **/go.sum
            **/go.mod
          go-version-file: 'go.mod'

      - name: Install linux dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

        #- name: garble
        #  run: go install mvdan.cc/garble@latest

        #- name: nsis
        # run: apt install nsis

        #- name: upx
        #  run: apt install upx

      - name: build
        run: |
          npm config get cache
          cd GoEasyDesigner
          wails build -debug 

      - uses: actions/upload-artifact@v3
        with:
          name: debug-${{ runner.os }}
          path: GoEasyDesigner/build/bin/GoEasyDesigner


  build-MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |

            /Users/runner/.npm
          key: ${{ runner.os }}-js-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-js-

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          cache-dependency-path: |
            **/go.sum
            **/go.mod
          go-version-file: 'go.mod'

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

        #- name: garble
        #  run: go install mvdan.cc/garble@latest

        #- name: nsis
        # run: apt install nsis

        #- name: upx
        #  run: apt install upx

      - name: build
        run: |
          npm config get cache
          cd GoEasyDesigner
          wails build -debug 

      - uses: actions/upload-artifact@v3
        with:
          name: debug-${{ runner.os }}
          path: GoEasyDesigner/build/bin/GoEasyDesigner.app

